### ISSUE TITLE
Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by dragoscv** [ElrondNetwork/dapp-core#256]
When using `import { DappUI, useGetLoginInfo } from '@elrondnetwork/dapp-core';` I get the following error in console:
```
Uncaught TypeError: Class extends value undefined is not a constructor or null
    at module.exports (keccak.js:5:1)
    at module.exports (index.js:6:1)
    at ./node_modules/keccak/js.js (js.js:1:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/@elrondnetwork/erdjs/out/signableMessage.js (signableMessage.js:12:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
```
I can't manage to find a solution, all that I'm doing is importing the library

Edit: In a TypeScript project it works, but in a simple JS react-app doesn't work

**Comment by StanislavSava** [comment]
This error usually indicates a circular dependency. Can you check if you have any dependencies in your app?

**Comment by StanislavSava** [comment]
@dragoscv any progress on this?
